# Generated by Django 3.1.6 on 2021-02-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210217_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='fname',
        ),
    ]
