# Generated by Django 3.1.6 on 2021-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210217_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('dest_ip', models.CharField(max_length=20)),
                ('filepath_with_name', models.CharField(max_length=20)),
            ],
        ),
    ]
